# Generated by Django 3.0.6 on 2020-05-22 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=200, unique=True)),
                ('stok_obat', models.BigIntegerField()),
                ('harga_obat', models.BigIntegerField()),
                ('dosis_obat', models.IntegerField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PemesananObat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_obat', models.IntegerField()),
                ('subtotal_obat', models.BigIntegerField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('idobat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoteker.Obat')),
                ('idrm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokter.RekamMedis')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
