# Generated by Django 3.0.5 on 2020-04-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akun',
            old_name='karyawan',
            new_name='pegawai',
        ),
    ]
