# Generated by Django 3.0.5 on 2020-04-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='is_apoteker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='akun',
            name='is_dokter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='akun',
            name='is_pegawaiadmin',
            field=models.BooleanField(default=False),
        ),
    ]
