# Generated by Django 3.0.5 on 2020-04-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.CharField(max_length=25, unique=True)),
                ('namapasien', models.CharField(max_length=200)),
                ('alamat', models.TextField(blank=True)),
                ('ttl', models.DateField()),
                ('notelp', models.CharField(max_length=15)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
